# secret configuration deployed to Kubernetes and loaded as environment variables
kind: Secret
apiVersion: v1
metadata:
  name: state-secrets
type: Opaque
data:

  ZOOKEEPER_HOST: {{ cat .Release.Name "-" "zookeeper" | nospace | b64enc }}
  KAFKA_HOST: {{ cat .Release.Name "-" "kafka" | nospace | b64enc }}

  MONGO_HOST: {{ cat .Release.Name "-" .Values.mongo.host | nospace | b64enc }}
