dependencies:
  - name: mongodb
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: ^0.4
    tags:
      - backend
      - all
  - name: kafka
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
    version: ^0.4
    tags:
      - backend
      - all