version: '2'
services:
    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            - KAFKA_HEAP_OPTS=-Xmx256M -Xms256M
#            - KAFKA_ADVERTISED_HOST_NAME=192.168.0.65
            - KAFKA_ADVERTISED_HOST_NAME=kafka
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
            - KAFKA_CREATE_TOPICS=thegame.user.create:1:1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - kafka_data:/kafka
        depends_on:
            - zookeeper
        networks:
            default:
                aliases:
                    - kafka
        logging:
            options:
                max-size: "10m"
                max-file: "10"
        restart: always
    cassandra:
        image: cassandra:latest
        ports:
            - "9042:9042"
        volumes:
            - data:/var/lib/cassandra
#        environment:
#            MAX_HEAP_SIZE: 128M
#            HEAP_NEWSIZE: 24M
        networks:
            default:
                aliases:
                    - cassandra
        logging:
            options:
                max-size: "10m"
                max-file: "10"
        restart: always
    user_create_worker:
        build: ./user/create
        environment:
            - KAFKA_PEERS=kafka:9092
#            - KAFKA_PEERS=192.168.0.65:9092
            - KAFKA_TOPICS=thegame.user.create
            - KAFKA_BUFFER_SIZE=1
            - KAFKA_PARTITION=0
            - KAFKA_CONSUMER_GROUP=user.create
            #- CASSANDRA_PEERS=192.168.0.65
            - CASSANDRA_PEERS=cassandra
            # 2 seconds
            - CASSANDRA_CONNECTION_TIMEOUT=2000
            - CASSANDRA_KEYSPACE=thegame
            - CASSANDRA_PROTOCOL_VERSION=3
            - CASSANDRA_CONSISTENCY=ONE
        depends_on:
            - kafka
            - cassandra
        networks:
            default:
                aliases:
                    - user_create_worker
        logging:
            options:
                max-size: "10m"
                max-file: "10"
        restart: always
volumes:
    kafka_data:
    data: