# secret configuration deployed to Kubernetes and loaded as environment variables
kind: Secret
apiVersion: v1
metadata:
  name: trading-server-secrets
type: Opaque
data:
  BITTREX_PUBLIC_KEY: {{ "dev" | b64enc }}
  BITTREX_PRIVATE_KEY: {{ "dev" | b64enc }}

  ZOOKEEPER_HOST: {{ cat .Release.Name "-" "zookeeper" | nospace | b64enc }}
  KAFKA_HOST: {{ cat .Release.Name "-" "kafka" | nospace | b64enc }}