apiVersion: v1
kind: Service
metadata:
  name: {{ template "trading-server.fullname" . }}
  labels:
    app: {{ template "trading-server.name" . }}
    chart: {{ template "trading-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3026
      nodePort: 30202
      protocol: TCP
  selector:
    app: {{ template "trading-server.name" . }}
