apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "kafka.fullname" . }}
  labels:
    app: {{ template "kafka.name" . }}
    chart: {{ template "kafka.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kafka.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "kafka.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: app
              containerPort: 9092
              protocol: TCP
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: {{ template "kafka.fullname" . }}
            - name: KAFKA_CREATE_TOPICS
              value: "platform:1:1,bot:1:1,market:1:1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "{{ template "zookeeper.fullname" . }}:2181"
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx256M -Xms256M"
            - name: KAFKA_MESSAGE_MAX_BYTES
              value: "2000000"