apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka.fullname" . }}
  labels:
    app: {{ include "kafka.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
spec:
  ports:
  - name: broker
    port: 9092
  selector:
    app: {{ include "kafka.name" . | quote }}