apiVersion: v1
kind: Service
metadata:
  name: {{ template "trading-spa.fullname" . }}
  labels:
    app: {{ template "trading-spa.name" . }}
    chart: {{ template "trading-spa.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: app
  selector:
    app: {{ template "trading-spa.name" . }}
